name: CI

on:
  push:
    branches:
      - main
   push_request:
    branches:
      - main

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: python3 -b

  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: python3 teste.py

  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "Finalizado"
      
    
